replicaCount: 2

config:
  appEnv: dev

image:
  repository: ghcr.io/pranay9-h/sample-app
  tag: latest

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
